.catalog:
  name: "ElasticSearch"
  version: "1.0.0"
  description: "ElasticSearch."
  questions:
    - variable: cluster_name
      description: "ElasticSearch集群的名称"
      label: "集群名称"
      type: "string"
      required: true
      default: "es"
elasticsearch:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "${cluster_name}"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "true"
        network.host: "_site_"