mysql:
  image: mysql:5.7
  ports:
    - "${PORT}:3306"
  labels:
    io.rancher.sidekicks: mysql-volume
  environment:
    - MYSQL_ROOT_PASSWORD=${mysql_root_password}
    - MYSQL_DATABASE=${mysql_database}
    - MYSQL_USER=${mysql_user}
    - MYSQL_PASSWORD=${mysql_password}
  volumes_from:
    - mysql-volume
mysql-volume:
  image: "busybox"
  volumes:
    - ${volume_work}:/var/lib/mysql
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/lib/mysql"]
