.catalog:
  name: "mysql"
  version: "5.7"
  description: "Create, organize, and discuss work with your team"
  questions:
    - variable: "PORT"
      type: "int"
      label: "Port Number"
      description: "Which port should mysql listen on?"
      default: 3306
    required: true
    - variable: "mysql_root_password"
      type: string
      required: true
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
    - variable: "mysql_database"
      type: string
      required: true
      label: "MySQL Database Name"
      description: "MySQL database to create"
    - variable: "mysql_user"
      type: string
      required: true
      description: "MySQL user for the created database"
      label: "MySQL DB User"
    - variable: "mysql_password"
      type: string
      required: true
      label: "MySQL DB Password"
      description: "Password for the MySQL user of the created database"
    - variable: "volume_work"
      description: "Work volume to save mysql data."
      label: "Work Volume:"
      required: true
      default: "/var/lib/mysql"
      type: "string"
