version: '2'
services:
  deliflow-artifactory-server:
    image: docker.bintray.io/jfrog/artifactory-oss:5.3.1
    labels:
      io.rancher.sidekicks: artifactory-data,artifactory-volume
      io.ranhcer.container.hostname_override: container_name
    ports:
      - "8081:8081"
    environment:
      - DB_TYPE=postgresql
      - DB_HOST=artifactory-data
      - DB_USER=artifactory
      - DB_PASSWORD=${password}
    volumes_from:
      - artifactory-volume
    links:
      - artifactory-data
    depends_on:
      - artifactory-data
  artifactory-data:
    image: postgres:9.4
    labels:
      io.ranhcer.container.hostname_override: container_name
    volumes:
      - ${volume_work}/artifactory/postgresql:/var/lib/postgresql/data
    volume_driver: ${volume_driver}
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=${password}
  artifactory-volume:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}/artifactory/data:/var/opt/jfrog/artifactory
    volume_driver: ${volume_driver}
    entrypoint: ["chown", "-R", "1000:1000", "/var/opt/jfrog/artifactory"]
  deliflow-sonarqube-server:
    image: sonarqube:5.6.6
    labels:
      io.rancher.sidekicks: sonarqube-data,sonarqube-volume
      io.ranhcer.container.hostname_override: container_name
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-data/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=${password}
    volumes_from:
      - sonarqube-volume
    links:
      - sonarqube-data
    depends_on:
      - sonarqube-data
  sonarqube-data:
    image: postgres:9.4
    labels:
      io.ranhcer.container.hostname_override: container_name
    volumes:
      - ${volume_work}/sonarqube/postgresql:/var/lib/postgresql/data
    volume_driver: ${volume_driver}
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=${password}
  sonarqube-volume:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}/sonarqube/data:/opt/sonarqube/data
    volume_driver: ${volume_driver}
    entrypoint: ["chown", "-R", "1000:1000", "/opt/sonarqube/data"]
