version: '2'
services:
  deliflow-artifactory-server:
    image: docker.bintray.io/jfrog/artifactory-oss:5.3.1
    labels:
      io.rancher.sidekicks: artifactory-data
      io.ranhcer.container.hostname_override: container_name
    ports:
      - "8081:8081"
    environment:
      - EXTRA_JAVA_OPTIONS=-Xmx4g
    volumes_from:
      - artifactory-data
  deliflow-sonarqube-server:
    image: sonarqube:5.6.6
    labels:
      io.rancher.sidekicks: sonarqube-data
      io.ranhcer.container.hostname_override: container_name
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://database/sonarqube?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=${password}
    volumes_from:
      - sonarqube-data
    links:
      - deliflow-mysql-server:database
  deliflow-mysql-server:
    image: mysql:5.7
    labels:
      io.rancher.sidekicks: mysql-data
      io.ranhcer.container.hostname_override: container_name
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=sonarqube
      - MYSQL_USER=sonarqube
      - MYSQL_PASSWORD=${password}
    volumes_from:
      - mysql-data
  artifactory-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}/artifactory:/var/opt/jfrog/artifactory
    volume_driver: ${volume_driver}
    entrypoint: ["chown", "-R", "1000:1000", "/var/opt/jfrog/artifactory"]
  sonarqube-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}/sonarqube:/opt/sonarqube/data
    volume_driver: ${volume_driver}
    entrypoint: ["chown", "-R", "1000:1000", "/opt/sonarqube/data"]
  mysql-data:
    image: busybox
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}/mysql:/var/lib/mysql
    volume_driver: ${volume_driver}
    entrypoint: ["chown", "-R", "1000:1000", "/var/lib/mysql"]
