jira:
  image: blacklabelops/jira:7.3.6
  ports:
    - "${PORT}:8080"
  labels:
    io.rancher.sidekicks: jira-volume
  environment:
    - 'JIRA_DATABASE_URL=mysql://${jira_db_username}@mysql/jira'
    - 'JIRA_DB_PASSWORD=${jira_db_password}'
  links:
    - mysql:mysql
  volumes_from:
    - jira-volume
jira-volume:
  image: "busybox"
  volumes:
    - ${jira_home}:/var/atlassian/jira
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/atlassian/jira"]
mysql:
  image: mysql:5.6
  labels:
    io.rancher.sidekicks: mysql-volume
  environment:
    - 'MYSQL_ROOT_PASSWORD=${jira_db_password}'
    - 'MYSQL_DATABASE=jira'
    - 'MYSQL_USER=${jira_db_username}'
    - 'MYSQL_PASSWORD=${jira_db_password}'
  volumes_from:
    - mysql-volume
mysql-volume:
  image: "busybox"
  volumes:
    - ${jira_home}/database:/var/lib/mysql
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/lib/mysql"]
