jenkins:
  image: "baselibrary/jenkins:2"
  ports:
    - "${PORT}:8080"
  labels:
    io.rancher.sidekicks: jenkins-config,jenkins-volume
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - jenkins-config
    - jenkins-volume
  entrypoint: /usr/local/bin/jenkins.sh
jenkins-config:
  image: rancher/jenkins-plugins:v0.1.1
jenkins-volume:
  image: "busybox"
  volumes:
    - ${volume_work}:/var/lib/jenkins
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "1000:1000", "/var/lib/jenkins"]
