catalog:
  name: jenkins
  version: 1.0
  description: jenkins server.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/var/lib/docker/jenkins"
    type: "string"
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: List of plugins in the format <plugin_name>[:<version>] one entry per line.
    default: |
      credentials
      git
      greenballs
      plain-credentials
      scm-api
      ssh-credentials
      ssh-slaves
      swarm
  - variable: "config"
    type: "multiline"
    label: "Config"
    description: "jenkins config."
    default: |
      ldap {
        enabled           = false
        server            = "ldap://1.2.3.4"
        rootDN            = "dc=foo,dc=com"
        userSearchBase    = "cn=users,cn=accounts"
        userSearchFilter  = ""
        groupSearchBase   = ""
        groupSearchFilter = ""
        groupSearchAttr   = ""
        managerDN         = "uid=serviceaccount,cn=users,cn=accounts,dc=foo,dc=com"
        managerPassword   = "password"
      }
jenkins:
  metadata:
    plugins: |
      ${plugins}
