catalog:
  name: jenkins
  version: 1.0
  description: jenkins server.
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data"
    label: "Work volume:"
    required: true
    default: "/var/lib/jenkins"
    type: "string"
  - variable: "plugins"
    type: "multiline"
    label: "List of Plugins"
    description: List of plugins in the format <plugin_name>[:<version>] one entry per line.
    default: |
      git
      subversion
      workflow-aggregator
      dashboard-view
      cloudbees-folder
      token-macro
      simple-theme
      docker
      ldap
      swarm
  - variable: "config"
    type: "multiline"
    label: "Config"
    description: "jenkins config."
    default: |
      security {
        ldap {
          enabled           = false
          server            = "ldap://ldap.example.com"
          rootDN            = "OU=Enterprise,OU=Principal,DC=corporate,DC=example,DC=com"
          userSearchBase    = "OU=Employees"
          userSearchFilter  = ""
          groupSearchBase   = "OU=Groups"
          groupSearchFilter = ""
          groupSearchAttr   = ""
          managerDN         = "CN=username,OU=Employees,OU=Enterprise,OU=Principal,DC=corporate,DC=example,DC=com"
          managerPassword   = "password"
        }
      }
jenkins:
  metadata:
    plugins: |
      ${plugins}
    config: |
      ${config}
