.catalog:
  name: jenkins
  version: 1.0-rancher1
  description: "jenkins server."
  questions:
  - variable: "PORT"
    type: "int"
    label: "Port Number"
    description: "Which port should Jenkins listen on?"
    default: 8080
    required: true
  - variable: "volume_work"
    description: "Work volume to save jenkins data."
    label: "Work Volume:"
    required: true
    default: "/var/lib/jenkins"
    type: "string"
  - variable: "plugins"
    type: "multiline"
    label: "Plugins"
    description: "List of plugins in the format <plugin_name>[:<version>] one entry per line."
    default: |
      git
      subversion
      workflow-aggregator
      dashboard-view
      cloudbees-folder
      token-macro
      simple-theme
      docker
      ldap
      locale
      swarm
  - variable: "config"
    type: "multiline"
    label: "Configurations"
    description: "Configurations of jenkins in the json format."
    default: |
    "security":{
      "ldap":{
        "server":"ldap://ldap.exapmle.com",
        "rootDN":"OU=Enterprise,OU=Principal,DC=corporate,DC=exapmle,DC=com",
        "userSearchBase":"OU=Users",
        "userSearchFilter":"sAMAccountName={0}",
        "groupSearchBase":"OU=Groups",
        "groupSearchFilter":"(& (cn={0}) (objectclass=group) )",
        "groupSearchAttr":"memberOf",
        "managerDN":"CN=username,DC=exapmle,DC=com",
        "managerPassword":"password by jenkins"
      }
    },
    "credentials":[
      {
        "id":"jenkins-slave-password",
        "description":"Jenkis Slave with Password Configuration",
        "username":"jenkins",
        "password":"jenkins"
      }
    ],
    "cloud":[
      {
        "docker":{
          "name":"docker",
          "severUrl":"unix:///var/run/docker.sock",
          "containerCapStr":"50",
          "connectTimeout":5,
          "readTimeout":15,
          "credentialsId":"",
          "templates":[
            {
              "image":"baselibrary/jenkins-slave:1.9",
              "dnsString":"",
              "network":"",
              "dockerCommand":"/usr/sbin/sshd -D",
              "volumesString":"/var/run/docker.sock:/var/run/docker.sock",
              "volumesFromString":"",
              "environmentsString":"",
              "lxcConfString":"",
              "hostname":"",
              "memoryLimit":null,
              "memorySwap":null,
              "cpuShares":null,
              "bindPorts":"",
              "bindAllPorts":false,
              "privileged":false,
              "tty":false,
              "labelString":"mono_slave",
              "remoteFs":"/var/lib/jenkins",
              "remoteFsMapping":"/var/lib/jenkins",
              "instanceCapStr":"10",
              "numExecutors":1,
              "removeVolume":false,
              "pullStrategy":"Pull once and update latest"
            }
          ]
        }
      }
    ]
jenkins:
  metadata:
    plugins: |
      ${plugins}
    config: |
      ${config}
