version: '2'
services:
  deliflow-cas-service:
    image: itherz/cas
    labels:
      io.ranhcer.container.hostname_override: container_name
    ports:
      - "8443:8443"
      - "9080:9080"
    environment:
      - HOST_NAME=${DELIFLOW_CAS_DOMIAN}
      - SERVER_NAME=https://${DELIFLOW_CAS_DOMIAN}:8443
      - LDAP_URL=ldap://deliflow-gocd-server:389
      - LDAP_ROOTDN="dc=deliflow,dc=com"
      - LDAP_BASEDN="dc=deliflow,dc=com"
      - LDAP_MANAGERDN="cn=admin,dc=deliflow,dc=com"
      - LDAP_MANAGERPASSWORD=deliflow
      - LDAP_USESTARTTLS=false
      - lLDAP_CONNECTTIMEOUT=3000
    external_links:
      - ${DELIFLOW_LDAP_HOST}:deliflow-gocd-server
