version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.3.1
    labels:
      io.rancher.sidekicks: artifactory-data
      io.ranhcer.container.hostname_override: container_name
    volumes_from:
      - artifactory-data
  artifactory-data:
    image: docker.bintray.io/jfrog/artifactory-oss:5.3.1
    labels:
      io.rancher.container.start_once: true
    volumes:
      - ${volume_work}:/var/opt/jfrog/artifactory
    volume_driver: ${volume_driver}
    command:
      - /bin/true
