lb:
  image: rancher/load-balancer-service
  ports:
    - 80:80
  labels:
    io.rancher.loadbalancer.target.jira: ${JIRA_HOST}=8080
    io.rancher.loadbalancer.target.confluence: ${CONFLUENCE_HOST}=8090
  links:
    - jira:jira
    - confluence:confluence

jira:
  image: blacklabelops/jira:7.3.6
  labels:
    io.rancher.sidekicks: jira-volume
  volumes_from:
    - jira-volume
  external_links:
   - ${database_link}:database
confluence:
  image: blacklabelops/confluence:6.1.3
  labels:
    io.rancher.sidekicks: confluence-volume
  volumes_from:
    - confluence-volume
  external_links:
    - ${database_link}:database
jira-volume:
  image: "busybox"
  volumes:
    - ${atlassian_home}/jira:/var/atlassian/jira
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "daemon:daemon", "/var/atlassian/jira"]
confluence-volume:
  image: "busybox"
  volumes:
    - ${atlassian_home}/confluence:/var/atlassian/confluence
  labels:
    io.rancher.container.start_once: true
  entrypoint: ["chown", "-R", "daemon:daemon", "/var/atlassian/confluence"]
