.catalog:
  name: "atlassian"
  version: "1.0.0"
  description: "Create, organize, and discuss work with your team"
  questions:
    - variable: JIRA_HOST
      label: "Jira Host"
      description: "Hostname of Jira instance reachable from external"
      type: string
      required: true
      default: "jira.example.com"

    - variable: CONFLUENCE_HOST
      label: "Confluence Host"
      description: "Hostname of Confluence instance reachable from external"
      type: string
      required: true
      default: "confluence.example.com"
    - variable: "atlassian_home"
      label: "Atlassian home directory"
      description: "The location to mount the Atlassian home directory on"
      type: "string"
      default: "/var/lib/atlassian"
      required: true
    - variable: "database_link"
      label: "Database"
      description: "Service link to the database. This will be mapped to the container as 'database'"
      type: "service"
      required: false
